---
title: "Final Project"
output: html_document
date: "2024-12-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scales)
library(kableExtra)
library(knitr)
library(gt)


#load(url("https://github.com/nbiler/Data-and-Society-Final/raw/refs/heads/main/NSDUH%20dataset/NSDUH_2023.Rdata"))
load("~/Documents/GitHub/Data-and-Society-Final/NSDUH dataset/NSDUH_2023.Rdata")
drug_df <- puf2023_102124
```
```{r, echo=FALSE}
drug_df %>% 
  select(ILLFLAG, ILLYR, ILLMON) %>%
  group_by(ILLFLAG, ILLYR, ILLMON) %>% 
  tally() %>% 
  mutate(whenuse = case_when(
    ILLFLAG == 0 ~ "Never used",
    ILLFLAG == 1 & ILLYR == 0 ~ "Used but not in past year",
    ILLYR == 1 & ILLMON == 0 ~ "Used in past year but not in past month",
    ILLMON == 1 ~ "Used in past month"
  )) %>%
  ungroup() %>% 
  mutate(prop = prop.table(n)) %>% 
  select(whenuse, prop) %>% 
  rename('When used illicit drugs last' = whenuse,
         'Percentage of individuals' = prop) %>% 
  gt() %>% 
  tab_header(
    title = "Drug Use Distribution",
    subtitle = "By Time of Use"
  ) %>% 
  fmt_percent(
    columns = "Percentage of individuals", 
    decimals = 2
  ) %>% 
  cols_label(
    `When used illicit drugs last` = "When Drugs Last Used",
    `Percentage of individuals` = "Percent"
  )
```
### By race for college students aged 18-22 over last 12 months
```{r, echo=FALSE}
drug_df %>% 
  filter(ENRLCOLLST2 == 1|
           ENRLCOLLST2 == 2) %>% 
  select(ILLYR, NEWRACE2) %>% 
  mutate(
    ILLYR_LAB = case_when(ILLYR == 0 ~ "Did not use in past year",
                                 ILLYR == 1 ~ "Used in past year"),
    
    NEWRACE2_LAB = case_when(
      NEWRACE2 == 1 ~ "White",
      NEWRACE2 == 2 ~ "Black/African American",
      NEWRACE2 == 3 ~ "Native American/Alaska Native",
      NEWRACE2 == 4 ~ "Native Hawaiian/Other Pacific Islander",
      NEWRACE2 == 5 ~ "Asian",
      NEWRACE2 == 6 ~ "More than one race",
      NEWRACE2 == 7 ~ "Hispanic"
    )) %>% 
  group_by(NEWRACE2_LAB, ILLYR_LAB) %>% 
  tally() %>% 
  mutate(prop_race = prop.table(n)) %>%
  filter(ILLYR_LAB == "Used in past year") %>%
  ggplot(aes(x = NEWRACE2_LAB, y = prop_race)) +
  geom_col(fill = "blue") +
  theme(axis.text.x = element_text(angle = 20, hjust = 1)) +
  labs(title = "Illicit drug use in past year by race for College Students aged 18-22",
       x = "Race",
       y = "Percentage which used in past year",
       caption = "Source: NSDUH") +
  scale_y_continuous(labels = scales::percent)
```

### Mental health in past month vs used drugs in last month for 18-29 years old
```{r, echo=FALSE}
drug_df %>% 
  filter(AGE3 == 4 |
           AGE3 == 5 |
           AGE3 == 6 |
           AGE3 == 7) %>% 
  select(KSSLR6MON, ILLMON) %>%
  mutate(ILLMON_LAB = factor(case_when(
    ILLMON == 0 ~ "Did not use in past month",
    ILLMON == 1 ~ "Used in past month"
  ), levels = c("Did not use in past month", "Used in past month"))) %>% 
  group_by(KSSLR6MON, ILLMON_LAB) %>% 
  tally() %>% 
  mutate(prop_KSS = prop.table(n)) %>% 
  filter(ILLMON_LAB == "Used in past month") %>% 
  ggplot(aes(x = KSSLR6MON, y = prop_KSS)) +
  geom_col(fill = "blue") +
  coord_cartesian(xlim = c(0, 24)) +
  scale_y_continuous(labels = scales::percent) +
  labs(title = "Illicit drug use in the past month vs scale of level of psycological distress for those 18-29 years old",
       subtitle = "Level of psycological distress calculated using the K6 questions on a scale from 0-24",
       caption = "Source: NSDUH",
       x = "Level of psycological distress",
       y = "Percentage which used in past month")
```

### If used in last month vs mental health 18-29 year olds
```{r, echo=FALSE}
drug_df %>% 
  filter(AGE3 == 4 |
           AGE3 == 5 |
           AGE3 == 6 |
           AGE3 == 7) %>% 
  select(KSSLR6MON, ILLMON) %>%
  filter(complete.cases(.)) %>% 
  mutate(ILLMON_LAB = factor(case_when(
    ILLMON == 0 ~ "Did not use in past month",
    ILLMON == 1 ~ "Used in past month"
  ), levels = c("Did not use in past month", "Used in past month"))) %>% 
  group_by(ILLMON_LAB) %>%
  summarise(avg.KSS = mean(KSSLR6MON)) %>% 
  ggplot(aes(x = ILLMON_LAB, y = avg.KSS, fill = ILLMON_LAB)) +
  geom_col(fill = "blue") +
  labs(title = "If used illicit drugs in past month vs average level of psycological distress for those 18-29 years old",
       subtitle = "Level of psycological distress calculated using the K6 questions on a scale from 0-24",
       caption = "Source: NSDUH",
       x = "If used illicit drugs in past month",
       y = "Average level of psycological distress")
```

### poverty last mon
```{r, echo=FALSE}
drug_df %>% 
  select(ILLMON, POVERTY3) %>% 
  filter(complete.cases(.)) %>% 
   mutate(ILLMON_LAB = factor(case_when(
    ILLMON == 0 ~ "Has not used in past month",
    ILLMON == 1 ~ "Used in past month"
  ), levels = c("Has not used in past month", "Used in past month")),
  POVERTY3_LAB = factor(case_when(
    POVERTY3 == 1 ~ "Living in poverty",
    POVERTY3 == 2 ~ "Income up to 2 times Federal Poverty Threshold",
    POVERTY3 == 3 ~ "Income above 2 times the Federal Poverty Threshold"),
    levels = c("Living in poverty", "Income up to 2 times Federal Poverty Threshold", "Income above 2 times the Federal Poverty Threshold"))) %>% 
  group_by(POVERTY3_LAB, ILLMON_LAB) %>% 
  tally() %>% 
  mutate(prop_pov = prop.table(n)) %>% 
  filter(ILLMON_LAB == "Used in past month") %>% 
  ggplot(aes(x = POVERTY3_LAB, y = prop_pov)) +
  geom_col(fill = "blue") +
  labs(title = "Poverty level vs if used drugs in past month",
       x = "Poverty level",
       y = "Percentage of individuals who used drugs in past month") +
  theme(axis.text.x = element_text(angle = 10, hjust = 1)) +
  scale_y_continuous(labels = scales::percent)
```
```{r eval= FALSE, include=FALSE}
#By sex
drug_df %>% 
  select(ILLFLAG, IRSEX) %>% 
  mutate(ILLFLAG_LAB = case_when(ILLFLAG == 0 ~ "Never Used",
                                 ILLFLAG == 1 ~ "Ever Used"),
         IRSEX_LAB = case_when(IRSEX == 1 ~ "Male",
                                IRSEX == 2 ~ "Female")) %>% 
  group_by(IRSEX_LAB, ILLFLAG_LAB) %>% 
  tally() %>% 
  mutate(prop.sex = prop.table(n)) %>% 
  ggplot(aes(x = IRSEX_LAB, y = prop.sex, fill = ILLFLAG_LAB)) +
  geom_col()
```
```{r eval= FALSE, include=FALSE}
# By sex for college students aged 18-22 over last 12 months
drug_df %>% 
  filter(ENRLCOLLST2 == 1|
           ENRLCOLLST2 == 2) %>%
  select(ILLYR, IRSEX) %>% 
  mutate(ILLYR_LAB = case_when(ILLYR == 0 ~ "Did not use in past year",
                                 ILLYR == 1 ~ "Used in past year"),
         IRSEX_LAB = case_when(IRSEX == 1 ~ "Male",
                                IRSEX == 2 ~ "Female")) %>% 
  group_by(IRSEX_LAB, ILLYR_LAB) %>% 
  tally() %>% 
  mutate(prop.sex = prop.table(n)) %>% 
  ggplot(aes(x = IRSEX_LAB, y = prop.sex, fill = ILLYR_LAB)) +
  geom_col()
```
```{r eval= FALSE, include=FALSE}
# By age
drug_df %>% 
  select(ILLYR, CATAG6) %>%
  mutate(CATAG6_LAB = case_when(CATAG6 == 1 ~ "12-17 Years Old",
                                CATAG6 == 2 ~ "18-25 Years Old",
                                CATAG6 == 3 ~ "26-34 Years Old",
                                CATAG6 == 4 ~ "35-49 Years Old",
                                CATAG6 == 5 ~ "50-64 Years Old",
                                CATAG6 == 6 ~ "65 or Older"),
         ILLYR_LAB = case_when(ILLYR == 0 ~ "Did not use in past year",
                                 ILLYR == 1 ~ "Used in past year")) %>% 
  group_by(CATAG6_LAB, ILLYR_LAB) %>% 
  tally() %>% 
  mutate(prop.age = prop.table(n)) %>% 
  ggplot(aes(x = CATAG6_LAB, y = prop.age, fill = ILLYR_LAB)) +
  geom_col()
```
```{r eval= FALSE, include=FALSE}
# By race
drug_df %>% 
  select(ILLFLAG, NEWRACE2) %>% 
  mutate(
    ILLFLAG_LAB = factor(case_when(
      ILLFLAG == 0 ~ "Never Used",
      ILLFLAG == 1 ~ "Ever Used"
    ), levels = c("Never Used", "Ever Used")),
    
    NEWRACE2_LAB = case_when(
      NEWRACE2 == 1 ~ "NonHisp White",
      NEWRACE2 == 2 ~ "NonHisp Black/Afr Am",
      NEWRACE2 == 3 ~ "NonHisp Native Am/AK Native",
      NEWRACE2 == 4 ~ "NonHisp Native HI/Other Pac Is",
      NEWRACE2 == 5 ~ "NonHisp Asian",
      NEWRACE2 == 6 ~ "NonHisp more than one race",
      NEWRACE2 == 7 ~ "Hispanic"
    )) %>% 
  group_by(NEWRACE2_LAB, ILLFLAG_LAB) %>% 
  tally() %>% 
  mutate(prop_race = prop.table(n)) %>% 
  ggplot(aes(x = NEWRACE2_LAB, y = prop_race, fill = ILLFLAG_LAB)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  

```
```{r eval= FALSE, include=FALSE}
# By race for college students aged 18-22 over last 12 months for female
drug_df %>% 
  filter(ENRLCOLLST2 == 1|
           ENRLCOLLST2 == 2) %>% 
  filter(IRSEX == 2) %>% 
  select(ILLYR, NEWRACE2) %>% 
  mutate(
    ILLYR_LAB = case_when(ILLYR == 0 ~ "Did not use in past year",
                                 ILLYR == 1 ~ "Used in past year"),
    
    NEWRACE2_LAB = case_when(
      NEWRACE2 == 1 ~ "White",
      NEWRACE2 == 2 ~ "Black/African American",
      NEWRACE2 == 3 ~ "Native American/Alaska Native",
      NEWRACE2 == 4 ~ "Native Hawaiian/Other Pacific Islander",
      NEWRACE2 == 5 ~ "Asian",
      NEWRACE2 == 6 ~ "More than one race",
      NEWRACE2 == 7 ~ "Hispanic"
    )) %>% 
  group_by(NEWRACE2_LAB, ILLYR_LAB) %>% 
  tally() %>% 
  mutate(prop_race = prop.table(n)) %>% 
  ggplot(aes(x = NEWRACE2_LAB, y = prop_race, fill = ILLYR_LAB)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r eval= FALSE, include=FALSE}
# By race for college students aged 18-22 over last 12 months for male
drug_df %>% 
  filter(ENRLCOLLST2 == 1|
           ENRLCOLLST2 == 2) %>% 
  filter(IRSEX == 1) %>% 
  select(ILLYR, NEWRACE2) %>% 
  mutate(
    ILLYR_LAB = case_when(ILLYR == 0 ~ "Did not use in past year",
                                 ILLYR == 1 ~ "Used in past year"),
    
    NEWRACE2_LAB = case_when(
      NEWRACE2 == 1 ~ "White",
      NEWRACE2 == 2 ~ "Black/African American",
      NEWRACE2 == 3 ~ "Native American/Alaska Native",
      NEWRACE2 == 4 ~ "Native Hawaiian/Other Pacific Islander",
      NEWRACE2 == 5 ~ "Asian",
      NEWRACE2 == 6 ~ "More than one race",
      NEWRACE2 == 7 ~ "Hispanic"
    )) %>% 
  group_by(NEWRACE2_LAB, ILLYR_LAB) %>% 
  tally() %>% 
  mutate(prop_race = prop.table(n)) %>% 
  ggplot(aes(x = NEWRACE2_LAB, y = prop_race, fill = ILLYR_LAB)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r eval=FALSE, include=FALSE}
# Personal Income aged 18 and over
drug_df %>% 
  filter(AGE3 >= 4) %>% 
  select(ILLFLAG, IRPINC3) %>% 
  mutate(
  ILLFLAG_LAB = factor(case_when(
    ILLFLAG == 0 ~ "Never Used",
    ILLFLAG == 1 ~ "Ever Used"
  ), levels = c("Never Used", "Ever Used")),
  
  IRPINC3_LAB = factor(case_when(
    IRPINC3 == 1 ~ "Less than $10,000 (Including Loss)",
    IRPINC3 == 2 ~ "$10,000 - $19,999",
    IRPINC3 == 3 ~ "$20,000 - $29,999",
    IRPINC3 == 4 ~ "$30,000 - $39,999",
    IRPINC3 == 5 ~ "$40,000 - $49,999",
    IRPINC3 == 6 ~ "$50,000 - $74,999",
    IRPINC3 == 7 ~ "$75,000 or more"
  ), levels = c(
    "Less than $10,000 (Including Loss)",
    "$10,000 - $19,999",
    "$20,000 - $29,999",
    "$30,000 - $39,999",
    "$40,000 - $49,999",
    "$50,000 - $74,999",
    "$75,000 or more"
  ))
) %>% 
  group_by(IRPINC3_LAB, ILLFLAG_LAB) %>% 
  tally() %>% 
  mutate(prop_inc = prop.table(n)) %>% 
  ggplot(aes(x = IRPINC3_LAB, y = prop_inc, fill = ILLFLAG_LAB)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```
```{r eval= FALSE, include=FALSE}
# Family Income
drug_df %>%
  select(ILLFLAG, IRFAMIN3) %>% 
  mutate(
  ILLFLAG_LAB = factor(case_when(
    ILLFLAG == 0 ~ "Never Used",
    ILLFLAG == 1 ~ "Ever Used"
  ), levels = c("Never Used", "Ever Used")),
  
  IRFAMIN3_LAB = factor(case_when(
    IRFAMIN3 == 1 ~ "Less than $10,000 (Including Loss)",
    IRFAMIN3 == 2 ~ "$10,000 - $19,999",
    IRFAMIN3 == 3 ~ "$20,000 - $29,999",
    IRFAMIN3 == 4 ~ "$30,000 - $39,999",
    IRFAMIN3 == 5 ~ "$40,000 - $49,999",
    IRFAMIN3 == 6 ~ "$50,000 - $74,999",
    IRFAMIN3 == 7 ~ "$75,000 or more"
  ), levels = c(
    "Less than $10,000 (Including Loss)",
    "$10,000 - $19,999",
    "$20,000 - $29,999",
    "$30,000 - $39,999",
    "$40,000 - $49,999",
    "$50,000 - $74,999",
    "$75,000 or more"
  ))
) %>% 
  group_by(IRFAMIN3_LAB, ILLFLAG_LAB) %>% 
  tally() %>% 
  mutate(prop_inc = prop.table(n)) %>% 
  ggplot(aes(x = IRFAMIN3_LAB, y = prop_inc, fill = ILLFLAG_LAB)) +
  geom_col() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_cartesian(ylim = c(0.4, 0.6))
```
```{r eval= FALSE, include=FALSE}
# By highest level of education 24 and older
drug_df %>% 
  select(AGE3, ILLFLAG, EDUHIGHCAT) %>% 
  filter(AGE3 >= 6) %>% 
  mutate(ILLFLAG_LAB = factor(case_when(
    ILLFLAG == 0 ~ "Never Used",
    ILLFLAG == 1 ~ "Ever Used"
  ), levels = c("Never Used", "Ever Used")),
  EDUHIGHCAT_LAB = factor(case_when(
    EDUHIGHCAT == 1 ~ "Less high school",
    EDUHIGHCAT == 2 ~ "High school grad",
    EDUHIGHCAT == 3 ~ "Some coll/Assoc Dg",
    EDUHIGHCAT == 4 ~ "College graduate"),
    levels = c("Less high school", "High school grad",
               "Some coll/Assoc Dg", "College graduate")
  )) %>% 
  group_by(EDUHIGHCAT_LAB, ILLFLAG_LAB) %>% 
  tally() %>% 
  mutate(prop_EDUC = prop.table(n)) %>% 
  ggplot(aes(x = EDUHIGHCAT_LAB, y = prop_EDUC, fill = ILLFLAG_LAB)) +
  geom_col()
  
```
```{r eval= FALSE, include=FALSE}
# By sexuality
drug_df %>% 
  select(ILLFLAG, SEXIDENT22) %>% 
  filter(SEXIDENT22 <= 5) %>% 
  mutate(ILLFLAG_LAB = factor(case_when(
    ILLFLAG == 0 ~ "Never Used",
    ILLFLAG == 1 ~ "Ever Used"
  ), levels = c("Never Used", "Ever Used")),
  SEXIDENT22_LAB = case_when(SEXIDENT22 == 1 ~ "Heterosexual",
                             SEXIDENT22 == 2 ~ "LGBTQ+",
                             SEXIDENT22 == 3 ~ "LGBTQ+",
                             SEXIDENT22 == 4 ~ "LGBTQ+",
                             SEXIDENT22 == 5 ~ "LGBTQ+")) %>% 
  group_by(SEXIDENT22_LAB, ILLFLAG_LAB) %>% 
  tally() %>% 
  mutate(prop_sex = prop.table(n)) %>% 
  ggplot(aes(x = SEXIDENT22_LAB, y = prop_sex, fill = ILLFLAG_LAB)) +
  geom_col()
```
```{r eval= FALSE, include=FALSE}
# If served in US armed forces
drug_df %>% 
  select(ILLFLAG, SERVICE) %>% 
  mutate(ILLFLAG_LAB = factor(case_when(
    ILLFLAG == 0 ~ "Never Used",
    ILLFLAG == 1 ~ "Ever Used"
  ), levels = c("Never Used", "Ever Used")),
  SERVICE_LAB = case_when(SERVICE == 1 ~ "Yes",
                          SERVICE == 2 ~ "No")) %>% 
    filter(complete.cases(.)) %>% 
  group_by(SERVICE_LAB, ILLFLAG_LAB) %>% 
  tally() %>% 
  mutate(prop_SERVICE = prop.table(n)) %>% 
  ggplot(aes(x = SERVICE_LAB, y = prop_SERVICE, fill = ILLFLAG_LAB)) +
  geom_col()
```
```{r eval= FALSE, include=FALSE}
# Mental health in past month vs used drugs in last month
drug_df %>% 
  select(KSSLR6MON, ILLMON) %>%
  mutate(ILLMON_LAB = factor(case_when(
    ILLMON == 0 ~ "Did not use in past month",
    ILLMON == 1 ~ "Used in past month"
  ), levels = c("Did not use in past month", "Used in past month"))) %>% 
  group_by(KSSLR6MON, ILLMON_LAB) %>% 
  tally() %>% 
  mutate(prop_KSS = prop.table(n)) %>% 
  ggplot(aes(x = KSSLR6MON, y = prop_KSS, fill = ILLMON_LAB)) +
  geom_col()
```
```{r eval = FALSE, include=FALSE}
# If used in last month vs mental health
drug_df %>% 
  select(KSSLR6MON, ILLMON) %>%
  filter(complete.cases(.)) %>% 
  mutate(ILLMON_LAB = factor(case_when(
    ILLMON == 0 ~ "Did not use in past month",
    ILLMON == 1 ~ "Used in past month"
  ), levels = c("Did not use in past month", "Used in past month"))) %>% 
  group_by(ILLMON_LAB) %>%
  summarise(avg.KSS = mean(KSSLR6MON)) %>% 
  ggplot(aes(x = ILLMON_LAB, y = avg.KSS, fill = ILLMON_LAB)) +
  geom_col()
```
```{r eval=FALSE, include=FALSE}
# Employment over 18
drug_df %>% 
  select(IRWRKSTAT18, ILLMON) %>% 
   mutate(ILLMON_LAB = factor(case_when(
    ILLMON == 0 ~ "Did not use in past month",
    ILLMON == 1 ~ "Used in past month"
  ), levels = c("Did not use in past month", "Used in past month")),
  IRWRKSTAT18_LAB = case_when(
    IRWRKSTAT18 == 1 ~ "Employed",
    IRWRKSTAT18 == 2 ~ "Employed",
    IRWRKSTAT18 == 3 ~ "Unemployed")) %>% 
  group_by(IRWRKSTAT18_LAB, ILLMON_LAB) %>% 
  tally() %>% 
  mutate(prop_work = prop.table(n)) %>% 
  ggplot(aes(x = IRWRKSTAT18_LAB, y = prop_work, fill = ILLMON_LAB)) +
  geom_col()
```